aspTaskManagement/Controllers/AdminController.cs
using aspTaskManagement.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aspTaskManagement.Controllers
{   
    [Authorize(Roles ="SuperAdmin, Admin")]
    public class AdminController : Controller
    {

        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateUser(FormCollection form)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

            if (ModelState.IsValid)
            {
                string UserName = form["txtEmail"];
                string email = form["txtEmail"];
                string pwd = form["txtPassword"];

                //***********************************
                //Create Users Profile
                Profile profile = new Profile();
                profile.Username = UserName;
                context.Profiles.Add(profile);
                context.SaveChanges();
                //***********************************

                //create new  user
                var user = new ApplicationUser();
                user.UserName = UserName;
                user.Email = email;


                var newUser = userManager.Create(user, pwd); 
                return Redirect("/Home");
            }

            return View(form);
        }

        public ActionResult AssignRole()
        {

            ViewBag.Email = context.Users.Select(r => new SelectListItem { Value = r.Email, Text = r.UserName }).ToList();
            ViewBag.Roles = context.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();

            return View();
        }

        [HttpPost]
        public ActionResult AssignRole(FormCollection form)
        {
            string username = form["Email"];
            string rolname = form["RoleName"];
            ApplicationUser user = context.Users.Where(u=>u.UserName.Equals(username, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            userManager.AddToRole(user.Id, rolname);
            return View("Index");
        }

        [HttpPost]
        public ActionResult NewRole(FormCollection form)
        {
            string roleName = form["RoleName"];
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
            if (!roleManager.RoleExists(roleName))
            {
                //create super admin
                var role = new IdentityRole(roleName);
                roleManager.Create(role);
            }

            return View("Index");
        }

        public ActionResult CreateRole()
        {
            return View();
        }

      
        public ActionResult EditProfile(RegisterViewModel model)
        {
            string id = User.Identity.GetUserId();

            ApplicationDbContext context = new ApplicationDbContext();

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

            var getUser = userManager.FindById(id);
            if (getUser == null)
            {
                return HttpNotFound();
            }

           

            model.Email = getUser.Email;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult postProfile([Bind(Include ="Email")]  RegisterViewModel model)
        {
            string Email = model.Email;

            if (ModelState.IsValid)
            {


            }

            return View(model);
        }

        [HttpGet]
        public ActionResult UsersList()
        {

            var userList = context.Users.ToList();

            List<ApplicationUser> _userList = new List<ApplicationUser>();

            _userList.AddRange(userList);

            return View(_userList);
        }

    }
}

aspTaskManagement/Views/Admin/AssignRole.cshtml
@{
    ViewBag.Title = "AssignRole";
}

<h2>Assign Role</h2>

@using (Html.BeginForm("AssignRole", "Admin", FormMethod.Post))
{
<div class="row">
    <div class="col-lg-6">
        <label class="control-label">User name</label>
        @*<input type="text" name="txtUserName" value="" class="form-control" />*@
        @Html.DropDownList("Email", (IEnumerable<SelectListItem>)ViewBag.Email,"---Select Users---", new {@class= "form-control" })
    </div>
    <div class="col-lg-6">
        <label class="control-label">User role</label>
        @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "---Select Role---", new {@class ="form-control" })
    </div>
    <div class="col-md-12">
        <br /><br />
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary">@Html.ActionLink("Back", "Index", "Admin")</button>
    </div>
</div>

}

aspTaskManagement/Views/Admin/CreateRole.cshtml
@{
    ViewBag.Title = "CreateRole";
}
<br />

<h2>CreateRole</h2>

@using (Html.BeginForm("NewRole", "Admin", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <label class="control-label">Role Name</label>
            <input type="text" class="form-control" name="RoleName" value="" />
        </div>
        <div class="col-md-6">
            <br />
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </div>
    <br />
    <p>@Html.ActionLink("Back", "Index", "Admin")</p>
}

aspTaskManagement/Views/Admin/CreateUser.cshtml
@{
    ViewBag.Title = "CreateUser";
}
<br />
<p>@Html.ActionLink("Back", "Index", "Admin")</p>
<h2 class="text-center">Create User</h2>

@using (Html.BeginForm("CreateUser", "Admin", FormMethod.Post))
{
<div class="row">
    <div class="col-md-12">
        <label class="control-label">User Email</label>
        <input type="text" name="txtEmail" class="form-control"/>
    </div>
    <div class="col-md-12"><br /><br />
        <label class="control-label">Password</label>
        <input  type="password" name="txtPassword" class="form-control"/>
    </div>
</div>
 <br />
<div class="row">
    <div class="col-md-12">
        <button type="submit" value="Submit" class="btn btn-primary">Save</button>
    </div>
</div>

}

aspTaskManagement/Views/Admin/EditProfile.cshtml
@model aspTaskManagement.Models.RegisterViewModel
@{
    ViewBag.Title = "EditProfile";
}

<h2>Edit Profile</h2>

@*@using (Html.BeginForm("postProfile", "Admin"))
{
    @Html.EditorFor(model => model.Email)
    @Html.EditorFor(model =>model.Password);
    @Html.EditorFor(model=>model.ConfirmPassword);
    <input type="submit" value="Save" />
}*@

aspTaskManagement/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<li>@Html.ActionLink("Create Role", "CreateRole", "Admin")</li>
<li>@Html.ActionLink("Create User", "CreateUser", "Admin")</li>
<li>@Html.ActionLink("Assign Role", "AssignRole", "Admin")</li>
<li>@Html.ActionLink("Edit Profile", "EditProfile", "Admin")</li>
<li>@Html.ActionLink("User List", "UsersList", "Admin")</li>

aspTaskManagement/Views/Admin/UsersList.cshtml
@model IEnumerable<aspTaskManagement.Models.ApplicationUser>

@{
    ViewBag.Title = "UsersList";
}
<br />
<p>@Html.ActionLink("Back", "Index", "Admin")</p>

<h2 class="text-center">UsersList</h2>
<br /><br />
<table class="table">
    <tr class="text-center">
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr class="text-center">
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>